jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Build steps omitted for brevity
      - name: Copy build artifacts from Docker container
        run: |
          docker cp app_build:/usr/src/app/dist ./dist
          ls -la ./dist/
      - name: Upload dist as artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist-artifact
          path: ./dist

  package:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Download dist artifact
        uses: actions/download-artifact@v2
        with:
          name: dist-artifact
          path: ./dist
      # Setup Node.js and pkg install steps omitted for brevity
      - name: Build executable using pkg
        run: |
          ls -la ./dist
          pkg -t ${{ env.PKG_TARGET }} ./dist/main.js
        env:
          PKG_CACHE_PATH: './.pkg-cache'
      # Upload artifact step omitted for brevity
